// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models;

[Table("beneficios")]
public partial class Beneficio
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("valor_beneficio", TypeName = "decimal(9, 2)")]
    public decimal? ValorBeneficio { get; set; }

    [Column("status")]
    public byte? Status { get; set; }
}