// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models;

[Table("folha_pagamentos")]
public partial class FolhaPagamento
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("colaborador_id")]
    public int? ColaboradorId { get; set; }

    [Column("horas_extras")]
    public int? HorasExtras { get; set; }

    [Column("inss", TypeName = "decimal(9, 2)")]
    public decimal? Inss { get; set; }

    [Column("outras_deducoes", TypeName = "decimal(9, 2)")]
    public decimal? OutrasDeducoes { get; set; }

    [Column("referencia", TypeName = "date")]
    public DateTime? Referencia { get; set; }

    [Column("data_emissao", TypeName = "datetime")]
    public DateTime? DataEmissao { get; set; }

    [ForeignKey("ColaboradorId")]
    [InverseProperty("FolhaPagamentos")]
    public virtual Colaboradores Colaborador { get; set; }
}