// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models;

[Table("reservas")]
public partial class Reserva
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("responsavel")]
    [StringLength(255)]
    public string Responsavel { get; set; }

    [Column("data_reserva", TypeName = "datetime")]
    public DateTime? DataReserva { get; set; }

    [Column("espaco", TypeName = "int")]
    public int Espaco { get; set; }

    [Column("qtde_horas", TypeName = "int")]
    public int QtdeHoras { get; set; }

    [Column("valor", TypeName = "decimal(9, 2)")]
    public decimal? Valor { get; set; }

    [Column("confirmado")]
    public byte? Confirmado { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }
}